language: go
sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git build-essential

jobs:
  include:
    - stage: build docker images 
      script: make docker.io/vdemeester/kobw-builder
    - stage: login to docker
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: push docker images
      if: branch = master
      script: docker push docker.io/vdemeester/kobw-base
    - if: branch = master
      script: docker push docker.io/vdemeester/kobw-builder
